name: Release

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14.18.0
        cache: 'yarn'
    - name: Install npm dependencies
      run: yarn install --frozen-lockfile
    - name: Run build task
      run: yarn build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_PRIVACY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.LINODE_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.LINODE_REMOTE_USER }}
          TARGET: ${{ secrets.LINODE_REMOTE_STAGE_TARGET }}
          EXCLUDE: ".github"
    - name: Reload web server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_REMOTE_HOST }}
        username: ${{ secrets.LINODE_REMOTE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVACY_KEY }}
        script: bash reload.sh